apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: vaccine-pool
  namespace: kafka
  labels:
    strimzi.io/cluster: vaccine-cluster 
spec:
  replicas: 1 
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        deleteClaim: false
 

---

# 2. The Cluster Configuration (Listeners & Config)
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: vaccine-cluster
  namespace: kafka
  annotations:
    strimzi.io/node-pools: "enabled"
    strimzi.io/kraft: "enabled"
spec:
  kafka:
    version: 4.1.0
    
    
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: nodeport # Optional: for external access
        tls: false
        
    config:
      # Critical for Single Node Stability
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      
  entityOperator:
    topicOperator: {}
    userOperator: {}