apiVersion: v1
kind: Secret
metadata:
  name: vaccine-secrets
  namespace: kafka
type: Opaque
stringData:
  postgres-user: "${POSTGRES_USER}"
  postgres-db: "vaccine_db"
  postgres-password: "${POSTGRES_PASSWORD}" 