apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaccine-producer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaccine-producer
  template:
    metadata:
      labels:
        app: vaccine-producer
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: producer
        image: ${DOCKER_REPO}/vaccine-producer:${IMAGE_TAG} 
        ports:                          # ← ADD THIS SECTION
        - name: metrics
          containerPort: 8000
        
        env:
        - name: KAFKA_BROKER
          value: "vaccine-cluster-kafka-bootstrap.kafka.svc:9092"
        - name: NUM_TRUCKS
          value: "50"  
        - name: ANOMALY_RATE
          value: "0.1" #10% chance 
        - name: PYTHONUNBUFFERED 
          value: "1"
        - name: DB_HOST
          value: "postgres-service.kafka.svc.cluster.local"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: vaccine-secrets
              key: postgres-db
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: vaccine-secrets
              key: postgres-user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: vaccine-secrets
              key: postgres-password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaccine-consumer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaccine-consumer
  template:
    metadata:
      labels:
        app: vaccine-consumer
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: consumer
        image: ${DOCKER_REPO}/vaccine-consumer:${IMAGE_TAG}
        ports:                          # ← ADD THIS SECTION
        - name: metrics
          containerPort: 8000
        env:
        - name: KAFKA_BROKER
          value: "vaccine-cluster-kafka-bootstrap.kafka.svc:9092"
        - name: DB_HOST
          value: "postgres-service.kafka.svc.cluster.local"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: vaccine-secrets
              key: postgres-db
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: vaccine-secrets
              key: postgres-user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: vaccine-secrets
              key: postgres-password